---
title: "Untitled"
output: html_document
---
```{r}
library(tidyverse)
library(readr)
library(readxl)
```

```{r}
MyCampus_Results <- read_csv("~/Desktop/MyCampus-Results_updated.csv")
```

```{r}
<<<<<<< HEAD
=======
library(readxl)
>>>>>>> 396c0364b32787527597ecd26504c880114bd136
Survey_Results_Master <- read_excel("~/Desktop/ClassroomData-master/Survey Results - Master.xlsx")
```

```{r}
read_excel("~/Desktop/smith scores.xlsx")
```

```{r}
custom <- separate(MyCampus_Results , customdata,into=c("a","b","c","d"),sep=",")
head(custom)
favorite <- custom %>%
  group_by(icon_id = "favorite_place")
```


```{r}
students_campus <- MyCampus_Results %>%
  filter(faculty == "na" )

faculty_campus <- MyCampus_Results %>%
  filter(faculty != "na")

faculty_campus %>%
  filter()
```


```{r}
<<<<<<< HEAD

=======
scores<-read_excel("~/Desktop/smith scores.xlsx")
```

```{r}
scores_only <- subset(scores,select=c(building_room_crn,TOTAL))
>>>>>>> 396c0364b32787527597ecd26504c880114bd136
```

